name: Laravel Deploy

on:
  push:
    branches: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/travel.eapply.site
            git fetch origin deploy
            git reset --hard origin/deploy
            npm ci
            npm run build
            docker compose exec -T app composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
            docker compose exec -T app php artisan migrate --force
            docker compose exec -T app php artisan optimize
            docker compose restart app
